name: Project9Line
favicon: null
layout_spectrum: 0.8205206044949591
typography_spectrum: 0.000795325729995966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5317816792521626
  lightness: 0.7916681729257107
  saturation: 0.7128882012329996
  rhythmicContrast: 0.36064343457110226
purpose: []
