name: Project9Line
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36285
title: Project9Line
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b9babc'
    - '#424244'
    - '#646567'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
